version: "3.5"

services:
  postgres:
    container_name: postgres_aps
    image: postgres:12.5
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-aps}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-admin}
    ports:
      - "5432:5432"
    restart: unless-stopped
    volumes:
      - postgres_cadastro_data:/var/lib/postgresql/data
    ports:
      - 5430:5432

volumes:
  postgres_cadastro_data:
