version: "3.5"

services:
  postgres-cadastro:
    container_name: aps-postgres-cadastro
    image: postgres:12.5
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-aps}
      POSTGRES_USER: ${POSTGRES_USER:-cadastro}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-cadastro}
    ports:
      - "5432:5432"
    restart: unless-stopped
    volumes:
      - postgres-cadastro-data:/var/lib/postgresql/data
    ports:
      - 5430:5432

  postgres-servico:
    container_name: aps-postgres-servico
    image: postgres:12.5
    environment:
      POSTGRES_DB: aps
      POSTGRES_USER: servico
      POSTGRES_PASSWORD: servico
    ports:
      - "5432:5432"
    restart: unless-stopped
    volumes:
      - postgres-servico-data:/var/lib/postgresql/data
    ports:
      - 5431:5432

# zookeeper and kafka configuration based on:
# https://github.com/confluentinc/kafka-images/blob/master/examples/kafka-single-node/docker-compose.yml

  zookeeper:
    container_name: aps-zookeeper
    image: confluentinc/cp-zookeeper:6.1.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    # "`-._,-'"`-._,-'"`-._,-'"`-._,-'"`-._,-'"`-._,-'"`-._,-'"`-._,-'"`-._,-
    # An important note about accessing Kafka from clients on other machines:
    # -----------------------------------------------------------------------
    #
    # The config used here exposes port 9092 for _external_ connections to the broker
    # i.e. those from _outside_ the docker network. This could be from the host machine
    # running docker, or maybe further afield if you've got a more complicated setup. 
    # If the latter is true, you will need to change the value 'localhost' in 
    # KAFKA_ADVERTISED_LISTENERS to one that is resolvable to the docker host from those 
    # remote clients
    #
    # For connections _internal_ to the docker network, such as from other services
    # and components, use kafka:29092.
    #
    # See https://rmoff.net/2018/08/02/kafka-listeners-explained/ for details
    # "`-._,-'"`-._,-'"`-._,-'"`-._,-'"`-._,-'"`-._,-'"`-._,-'"`-._,-'"`-._,-
    #
    container_name: aps-kafka
    image: confluentinc/cp-kafka:6.1.0
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

volumes:
  postgres-cadastro-data:
  postgres-servico-data:
