version: "3.5"

services:
  postgres-cadastro:
    container_name: aps-postgres-cadastro
    image: postgres:12.5
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-aps}
      POSTGRES_USER: ${POSTGRES_USER:-cadastro}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-cadastro}
    ports:
      - "5432:5432"
    restart: unless-stopped
    volumes:
      - postgres-cadastro-data:/var/lib/postgresql/data
    ports:
      - 5430:5432

  postgres-servico:
    container_name: aps-postgres-servico
    image: postgres:12.5
    environment:
      POSTGRES_DB: aps
      POSTGRES_USER: servico
      POSTGRES_PASSWORD: servico
    ports:
      - "5432:5432"
    restart: unless-stopped
    volumes:
      - postgres-servico-data:/var/lib/postgresql/data
    ports:
      - 5431:5432

volumes:
  postgres-cadastro-data:
  postgres-servico-data:
