CREATE SEQUENCE FATURA_CODIGO START 1;

CREATE TABLE FATURA (
  ID                              BIGINT Not Null,
  UID                             UUID Not Null,
  VERSION                         INTEGER Not Null,
  CODIGO                          INTEGER,
  CLIENTE_REPLICA_ID              BIGINT,
  DATA                            TIMESTAMP,
  VALOR_TOTAL                     NUMERIC(14, 4),
  CONSTRAINT FATURA_PK PRIMARY KEY (ID),
  CONSTRAINT FATURA_UID_UK UNIQUE (UID),
  CONSTRAINT FATURA_CODIGO_UK UNIQUE (CODIGO),
  CONSTRAINT FATURA_CLIENTE_REPLICA_FK FOREIGN KEY (CLIENTE_REPLICA_ID) REFERENCES CLIENTE_REPLICA (ID)
);

ALTER TABLE ORDEM_SERVICO ADD COLUMN
  FATURA_ID                       BIGINT;

ALTER TABLE ORDEM_SERVICO ADD
  CONSTRAINT ORDEM_SERVICO_FATURA_FK FOREIGN KEY (FATURA_ID) REFERENCES FATURA (ID);
