CREATE TABLE BAIXA (
  ID                              BIGINT Not Null,
  UID                             UUID Not Null,
  VERSION                         INTEGER Not Null,
  CLIENTE_REPLICA_ID              BIGINT,
  TIPO_BAIXA_ID                   BIGINT,
  DATA                            TIMESTAMP,
  VALOR                           NUMERIC(14, 4),
  OBSERVACAO                      CHARACTER VARYING(8192),
  CONSTRAINT BAIXA_PK PRIMARY KEY (ID),
  CONSTRAINT BAIXA_UID_UK UNIQUE (UID),
  CONSTRAINT BAIXA_CLIENTE_REPLICA_FK FOREIGN KEY (CLIENTE_REPLICA_ID) REFERENCES CLIENTE_REPLICA (ID),
  CONSTRAINT BAIXA_TIPO_BAIXA_FK FOREIGN KEY (TIPO_BAIXA_ID) REFERENCES TIPO_BAIXA (ID)
);
